import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });
import { useRouter } from "next/router";
export default function Home() {
  const router = useRouter();
  return (
    <main className={styles.main}>
      <footer className={styles.mynav}>
        <a
          href="https://ranarabees.pythonanywhere.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          {"  "}
          <img src="/favicon.png" alt="RanaVerse" className={styles.navlogo} />
        </a>
        <br />
        <button className={styles.mainbtn}>
          <a onClick={() => router.push("#quaid")} target="_blank">
            {" "}
            Quaid-E-Azam
          </a>
        </button>

        <button className={styles.mainbtn}>
          <a onClick={() => router.push("#allama")} target="_blank">
            {" "}
            Allama-Iqbal
          </a>
        </button>

        <button className={styles.mainbtn}>
          <a onClick={() => router.push("#sirsyed")} target="_blank">
            {" "}
            Sir-Syed-Ahmed-Khan
          </a>
        </button>

        <button className={styles.mainbtn}>
          <a onClick={() => router.push("#liaquat")} target="_blank">
            {" "}
            Liaquat-Ali-Khan
          </a>
        </button>
      </footer>
      <br />
      <Head>
        <title>Muslim Political Leaders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.center}>
        <div id="Hero">
          <center>
            <Image
              src="/favicon.ico"
              alt="back"
              width={200}
              height={200}
              className={styles.backLogo}
              priority
            />
          </center>
          <Image
            className={styles.logo}
            src="/favicon.png"
            alt="Next.js Logo"
            width={450}
            height={300}
            priority
          />{" "}
          <br />
          <br />
          <br />
          <br />
          <center>
            <div className={styles.thirteen}>
              <Image
                src="https://dailytimes.com.pk/assets/uploads/2018/08/28/1707020-quaidiazam-1525968344-471-640x480-1.jpg"
                alt="13"
                width={100}
                height={120}
                priority
              />
              br
            </div>
          </center>
        </div>
      </div>
      <div>
        <div className={styles.boxa}>
          <center className={styles.boxatitle}>
            <h1>
              <b>
                <em>About Quaid-E-Azam</em>
              </b>
              <center>
                <Image
                  className={styles.mylogo}
                  src="/rana.jpg"
                  alt="Next.js Logo"
                  width={75}
                  height={75}
                  priority
                />
              </center>
            </h1>
          </center>

          <center>
            <p className={styles.boxapara}>
              <em>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit
                cumque, fugit sapiente quisquam recusandae et perferendis
                mollitia voluptatem animi atque similique. Odit corporis
                voluptates iusto? Dolorum eligendi quidem libero odit!.
              </em>
              <br />
              <br />
              <em>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit
                cumque, fugit sapiente quisquam recusandae et perferendis
                mollitia voluptatem animi atque similique. Odit corporis
                voluptates iusto? Dolorum eligendi quidem libero odit!.
              </em>
              <br />
              <br />
              <em>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit
                cumque, fugit sapiente quisquam recusandae et perferendis
                mollitia voluptatem animi atque similique. Odit corporis
                voluptates iusto? Dolorum eligendi quidem libero odit!.
              </em>
              <br />
              <br />
              <em>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit
                libero odit!.
              </em>
              <br />
              <br />
            </p>
          </center>
        </div>
      </div>
      <div>
        <div className={styles.boxb}>
          <center className={styles.boxatitle}>
            <h1>
              <b>
                <em>About Allama-Iqbal</em>
              </b>
              <center>
                <Image
                  className={styles.mylogo}
                  src="http://4.bp.blogspot.com/_AdwQ4z13x00/S8WyDcPTf2I/AAAAAAAAA4Q/rCsUQiQSWfk/s1600/allama-iqbal.jpg"
                  alt="Next.js Logo"
                  width={75}
                  height={75}
                  priority
                />
              </center>
            </h1>
          </center>

          <center>
            <p className={styles.boxapara}>
              <em>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit
                cumque, fugit sapiente quisquam recusandae et perferendis
                mollitia voluptatem animi atque similique. Odit corporis
                voluptates iusto? Dolorum eligendi quidem libero odit!.
              </em>
              <br />
              <br />
              <em>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit
                cumque, fugit sapiente quisquam recusandae et perferendis
                mollitia voluptatem animi atque similique. Odit corporis
                voluptates iusto? Dolorum eligendi quidem libero odit!.
              </em>
              <br />
              <br />
              <em>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit
                cumque, fugit sapiente quisquam recusandae et perferendis
                mollitia voluptatem animi atque similique. Odit corporis
                voluptates iusto? Dolorum eligendi quidem libero odit!.
              </em>
              <br />
              <br />
              <em>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit
                libero odit!.
              </em>
              <br />
              <br />
            </p>
          </center>
        </div>
      </div>
      <div>
        <div className={styles.mythirteen}>
          <center>
            {" "}
            <Image
              className={styles.mylogo}
              src="/rana.jpg"
              alt="Next.js Logo"
              width={75}
              height={75}
              priority
            />
            <Image
              className={styles.mylogo}
              src="http://4.bp.blogspot.com/_AdwQ4z13x00/S8WyDcPTf2I/AAAAAAAAA4Q/rCsUQiQSWfk/s1600/allama-iqbal.jpg"
              alt="Next.js Logo"
              width={75}
              height={75}
              priority
            />
            <Image
              className={styles.mylogo}
              src="https://upload.wikimedia.org/wikipedia/commons/1/1a/Syed_Ahmad_Khan_1907.jpg"
              alt="Next.js Logo"
              width={75}
              height={75}
              priority
            />
            <Image
              className={styles.mylogo}
              src="https://cdn.britannica.com/44/99344-050-C693B336/Liaquat-Ali-Khan-Pakistan.jpg"
              alt="Next.js Logo"
              width={75}
              height={75}
              priority
            />
          </center>
        </div>

        <center className={styles.abouthead}>
          {" "}
          <h1> About Muslim Political Leaders </h1>
        </center>
        <h4>
          <center className={styles.aboutheadtext}>
            {" "}
            <p>^| 👻: About Our Muslim Political Leaders :👻 |^</p>{" "}
          </center>
          <Image
            className={styles.mylogo}
            src="https://i0.wp.com/infomazza.com/wp-content/uploads/2014/09/Quaid-e-Azam1.jpg?ssl=1"
            alt="Next.js Logo"
            width={75}
            height={75}
            priority
          />
          <center id="quaid">
            <h1>
              <em>
                <b className={styles.quadtitle}>{" Quaid-E-Azam "}</b>
              </em>
            </h1>
          </center>
          <br />
          <p className={styles.aboutparaquaid}>
            <h3>
              {" "}
              Mohammed Ali Jinnah, also called Qaid-i-Azam (Arabic: “Great
              Leader”)
            </h3>{" "}
            <br /> (born December 25, 1876?, Karachi, India [now in
            Pakistan]—died September 11, 1948, Karachi), Indian Muslim
            politician, who was the founder and first governor-general (1947–48)
            of Pakistan. <h3>Early years</h3> <br />
            Jinnah was the eldest of seven children of Jinnahbhai Poonja, a
            prosperous merchant, and his wife, Mithibai. His family was a member{" "}
            <br />
            of the Khoja caste, Hindus who had converted to Islam centuries
            earlier and who were followers of the Aga Khan. There is some
            question about Jinnah’s date of birth: although he maintained that
            <br />
            it was December 25, 1876, school records from Karachi (Pakistan)
            give a date of October 20, 1875. Britannica Quiz A Study of History:
            Who, What, Where, and When? After being taught at home, Jinnah was
            <br />
            sent in 1887 to the Sind Madrasat al-Islam (now Sindh Madressatul
            Islam University) in Karachi. Later he attended the Christian
            Missionary Society High School (also in Karachi), where at the age
            <br />
            of 16 he passed the matriculation examination of the University of
            Bombay (now University of Mumbai, in Mumbai, India). On the advice
            of an English friend, his father decided to send him to England to
            <br />
            acquire business experience. Jinnah, however, had made up his mind
            to become a barrister. In keeping with the custom of the time, his
            parents arranged for an early marriage for him before he left for
            <br />
            England. In London he joined Lincoln’s Inn, one of the legal
            societies that prepared students for the bar. In 1895, at the age of
            19, he was called to the bar. While in London Jinnah suffered two
            <br />
            severe bereavements—the deaths of his wife and his mother.
            Nevertheless, he completed his formal studies and also made a study
            of the British political system, frequently visiting the House of
            <br />
            Commons. He was greatly influenced by the liberalism of William E.
            Gladstone, who had become prime minister for the fourth time in
            1892, the year of Jinnah’s arrival in London. Jinnah also took a
            <br />
            keen interest in the affairs of India and in Indian students. When
            the Parsi leader Dadabhai Naoroji, a leading Indian nationalist, ran
            for the British Parliament, Jinnah and other Indian students worked
            <br />
            day and night for him. Their efforts were crowned with success:
            Naoroji became the first Indian to sit in the House of Commons. When
            Jinnah returned to Karachi in 1896, he found that his father’s
            <br />
            business had suffered losses and that he now had to depend on
            himself. He decided to start his legal practice in Bombay (now
            Mumbai), but it took him years of work to establish himself as a
            <br />
            lawyer. It was nearly 10 years later that he turned actively toward
            politics. A man without hobbies, he divided his interest between law
            and politics. Nor was he a religious zealot: he was a Muslim in a
            <br />
            broad sense and had little to do with sects. His interest in women
            was also limited, to Rattenbai (Rutti)—the daughter of Sir Dinshaw
            Petit, a Bombay Parsi millionaire—whom he married in 1918 over
            <br />
            tremendous opposition from her parents and others. The couple had
            one daughter, Dina, but the marriage proved an unhappy one, and
            Jinnah and Rutti soon separated. It was his sister Fatima who gave
            <br />
            him solace and company. Get a Britannica Premium subscription and
            gain access to exclusive content. Subscribe Now Mahmud Husain The
            Editors of Encyclopaedia Britannica
            <br />
            <br />
            <h3> Entry into Politics </h3>
            <br /> Jinnah first entered politics by participating in the 1906
            session of the Indian National Congress (Congress Party) held at
            Calcutta (now Kolkata), in which the party
            <br />
            began to split between those calling for dominion status and those
            advocating independence for India. Four years later he was elected
            to the Imperial Legislative Council—the beginning of a long and
            <br />
            distinguished parliamentary career. In Bombay he came to know, among
            other important Congress Party personalities, Gopal Krishna Gokhale,
            the eminent Maratha leader. Greatly influenced by those nationalist
            <br />
            politicians, Jinnah aspired during the early part of his political
            life to become “a Muslim Gokhale.” Admiration for British political
            institutions and an eagerness to raise the status of India in the
            <br />
            international community and to develop a sense of Indian nationhood
            among the peoples of India were the chief elements of his politics.
            At that time, he still looked upon Muslim interests in the context
            <br />
            of Indian nationalism. But, by the beginning of the 20th century,
            the conviction had been growing among the Muslims that their
            <br />
            interests demanded the preservation of their separate identity
            rather than amalgamation in the Indian nation that would for all
            practical purposes be Hindu. Largely to safeguard Muslim interests,
            <br />
            the All-India Muslim League was founded in 1906. But Jinnah remained
            aloof from it. Only in 1913, when authoritatively assured that the
            league was as devoted as the Congress Party to the political
            <br />
            emancipation of India, did Jinnah join the league. When the Indian
            Home Rule League was formed, he became its chief organizer in Bombay
            and was elected president of the Bombay branch. <br />
            <br />
            <h3>Political unity</h3>
            <br />
            Jinnah’s endeavours to bring about the political union of Hindus and
            Muslims earned him the title of “the best ambassador of Hindu-Muslim
            <br />
            unity,” an epithet coined by Gokhale. It was largely through his
            efforts that the Congress Party and the Muslim League began to hold
            their annual sessions jointly, to facilitate mutual consultation and
            <br />
            participation. In 1915 the two organizations held their meetings in
            Bombay and in 1916 in Lucknow, where the Lucknow Pact was concluded.
            Under the terms of the pact, the two organizations put their seal to
            <br />
            a scheme of constitutional reform that became their joint demand
            vis-à-vis the British government. There was a good deal of give and
            take, but the Muslims obtained one important concession in the shape
            <br />
            of separate electorates, already conceded to them by the government
            in 1909 but hitherto resisted by Congress. Meanwhile, a new force in
            Indian politics had appeared in the person of Mohandas (Mahatma)
            <br />
            Gandhi. Both the Home Rule League and the Congress Party had come
            under his sway. Opposed to Gandhi’s noncooperation movement and his
            essentially Hindu approach to politics, Jinnah left both the league
            <br />
            and the Congress Party in 1920. For a few years he kept himself
            aloof from the main political movements. He continued to be a firm
            believer in Hindu-Muslim unity and constitutional methods for the
            <br />
            achievement of political ends. After his withdrawal from Congress,
            he used the Muslim League platform for the propagation of his views.
            But during the 1920s the Muslim League, and with it Jinnah, had been
            <br />
            overshadowed by Congress and the religiously oriented Muslim
            Khilafat movement. When the failure of the noncooperation movement
            and the emergence of Hindu revivalist movements led to antagonism
            <br />
            and riots between Hindus and Muslims, the Muslim League began to
            lose strength and cohesion, and provincial Muslim leaders formed
            their own parties to serve their needs. Thus, Jinnah’s problem
            <br />
            during the following years was to convert the Muslim League into an
            enlightened, unified political body prepared to cooperate with other
            organizations working for the good of India. In addition, he had to
            <br />
            convince the Congress Party, as a prerequisite for political
            progress, of the necessity of settling the Hindu-Muslim conflict. To
            <br />
            bring about such a rapprochement was Jinnah’s chief purpose during
            the late 1920s and early 1930s. He worked toward this end within the
            legislative assembly, at the Round Table Conference in London
            <br />
            (1930–32), and through his “14 points,” which included proposals for
            a federal form of government, greater rights for minorities,
            one-third representation for Muslims in the central legislature,
            <br />
            separation of the predominantly Muslim Sindh region from the rest of
            the Bombay province, and introduction of reforms in the North-West
            Frontier Province. His failure to bring about even minor amendments
            <br />
            in the Nehru Committee proposals (1928) over the question of
            separate electorates and reservation of seats for Muslims in the
            legislatures frustrated him. He found himself in a peculiar position
            <br />
            at that time: many Muslims thought that he was too nationalistic in
            his policy and that Muslim interests were not safe in his hands,
            while the Congress Party would not even meet the moderate Muslim
            <br />
            demands halfway. Indeed, the Muslim League was a house divided
            against itself. The Punjab Muslim League repudiated Jinnah’s
            leadership and organized itself separately. In disgust, Jinnah
            <br />
            decided to settle in England. From 1930 to 1935 he remained in
            London, devoting himself to practice before the Privy Council. But
            when constitutional changes were in the offing, he was persuaded to
            <br />
            return home to head a reconstituted Muslim League. Soon preparations
            started for the elections under the Government of India Act of 1935.
            Jinnah was still thinking in terms of cooperation between the Muslim
            <br />
            League and the Hindu-controlled Congress Party and with coalition
            governments in the provinces. But the elections of 1937 proved to be
            a turning point in the relations between the two organizations.
            <br />
            Congress obtained an absolute majority in six provinces, and the
            league did not do particularly well. The Congress Party decided not
            to include the league in the formation of provincial governments,
            <br />
            and exclusive all-Congress governments were the result. Relations
            between Hindus and Muslims started to deteriorate, and soon Muslim
            discontent became boundless.
            <br />
            <br />
            <h3> Creator of Pakistan </h3>
            <br />
            Jinnah had originally been dubious about the practicability of
            Pakistan, an idea that the poet and philosopher Sir Muhammad Iqbal
            had propounded to the Muslim League
            <br />
            conference of 1930, but before long he became convinced that a
            Muslim homeland on the Indian subcontinent was the only way of
            safeguarding Muslim interests and the Muslim way of life. It was not
            <br />
            religious persecution that he feared so much as the future exclusion
            of Muslims from all prospects of advancement within India, as soon
            as power became vested in the close-knit structure of Hindu social
            <br />
            organization. To guard against that danger, he carried out a
            nationwide campaign to warn his coreligionists of the perils of
            their position, and he converted the Muslim League into a powerful
            <br />
            instrument for unifying the Muslims into a nation. At that point,
            Jinnah emerged as the leader of a renascent Muslim nation. Events
            began to move fast. On March 22–23, 1940, in Lahore, the league
            <br />
            adopted a resolution to form a separate Muslim state, Pakistan. The
            Pakistan idea was at first ridiculed and then tenaciously opposed by
            the Congress Party. But it captured the imagination of the Muslims.
            <br />
            Pitted against Jinnah were many influential Hindus, including Gandhi
            and Jawaharlal Nehru. And the British government seemed to be intent
            on maintaining the political unity of the Indian subcontinent. But
            <br />
            Jinnah led his movement with such skill and tenacity that ultimately
            both the Congress Party and the British government had no option but
            to agree to the partitioning of India. Pakistan thus emerged as an
            <br />
            independent state in 1947.{" "}
            <a
              href="https://cdn.britannica.com/45/100345-050-E077D5BB/Tomb-Mohammed-Ali-Jinnah-Karachi-Pakistan.jpg"
              target="_rana"
            >
              : tomb of Mohammed Ali Jinnah :<br />
            </a>
            became the first head of the new state. Faced with the serious
            problems of a young country, he tackled Pakistan’s problems with
            <br />
            authority. He was not regarded as merely the governor-general. He
            was revered as the father of the nation. He worked hard until
            overpowered by age and disease in Karachi, the place of his birth,
            <br />
            in 1948.
          </p>

          <Image
            className={styles.mylogo}
            src="https://rekhta.pc.cdn.bitgravity.com/Images/Shayar/allama-iqbal.png"
            alt="Next.js Logo"
            width={75}
            height={75}
            priority
          />
          <center id="allama">
            <h1>
              <em>
                <b className={styles.allamatitle}>{" Allama-Iqbal "}</b>
              </em>
            </h1>
          </center>
          <br />

          <p className={styles.aboutparaallama}>
            Allama Iqbal was our great National hero. He is the poet of East.{" "}
            <br /> He was born in Sialkoat on November 9, 1877. He received his
            early education in Sialkoat. He passed intermediate examination from
            Murrey College Sialkoat. Then he went to Lahore for higher studies.{" "}
            <br />
            After that, he went to England and Germany. He got Ph.D. in
            Philosophy. He wrote many poems in praise of the Muslim culture.{" "}
            <br /> He reminded the Muslims of their glorious past. The names of
            some of his books are Bang-e-Dara, Bal-e-Jibril, Payam-e-Mashriq and{" "}
            <br />
            Asrar-e-Khudi. He gave the idea of Pakistan. He requested
            Quaid-e-Azam to accept the leadership of the Muslims. He was, <br />
            indeed, a great leader. He died on April 21, 1938. He was buried
            near the Badshahi Mosque in Lahore. <br />
          </p>
          <Image
            className={styles.mylogo}
            src="https://www.dailypioneer.com/uploads/2018/story/images/big/the-real-sir-syed--a-british-agent-2018-10-22.jpg"
            alt="Next.js Logo"
            width={75}
            height={75}
            priority
          />
          <center id="sirsyed">
            <h1>
              <em>
                <b className={styles.syedtitle}>{" Sir-Syed-Ahmed-Khan "}</b>
              </em>
            </h1>
          </center>
          <br />

          <p className={styles.aboutparasyad}>
            The great leader and founder of Pakistan. His real name is Mohammad{" "}
            <br />
            Ali Jinnah but widely known as Quaid-e-Azam or Baba-e-Qoum which
            means the father of the nation. Quaid-e-Azam was born on the 25th of
            December in Karachi, in 1876. Quaid-e-Azam was a successful lawyer{" "}
            <br />
            as well as a politician. Quaid-e-Azam’s father’s name was Jinnah
            Poonja and his mother’s name was Mithibai. Quaid-e-Azam belonged to
            a rich merchant family. Quaid-e-Azam received his early education{" "}
            <br />
            from Sindh Madrasa-ul-Islam and a Christian missionary school. He
            was sent to England at the mere age of 16 for higher education and
            later got admission to Lincoln’s Inn Law school to study Law. He{" "}
            <br />
            returned home after studying abroad, then took over managing his
            family business. A few years later, Quaid-e-Azam opened his law firm
            and became a successful lawyer and by 1900, he was appointed as a{" "}
            <br />
            magistrate for the region’s presidency. During this time, Jinnah
            noticed that Hindus and Muslims were united against England, but the
            Hindu leaders had set their interests somewhere else. Soon after{" "}
            <br />
            this Quaid-e-Azam left behind practicing law and went on to join
            political parties so he could take up leadership positions among
            organizations that planned to form Pakistan’s identity. He started{" "}
            <br />
            his political career with Indian National Congress in 1906, then
            after a time span of 7 years, Jinnah joined the Muslim League.
            Quaid-e-Azam was a man with great qualities and leadership. He was a{" "}
            <br />
            human rights activist who constantly fought for the rights of
            Muslims and dedicated his whole life to the liberation of Pakistan.
            He tirelessly worked for the Muslims struggling in India and <br />
            presented their concerns in the 14 points which were rejected by
            Congress. He endured many hardships for the formation of Pakistan
            and the rights of Muslims, but he did not give up. However, his{" "}
            <br />
            efforts did not go unrewarded. Quaid-e-Azam was a man of his word
            and one of the greatest spokesmen. Mahatma Gandhi called
            Quaid-e-Azam “an impossible man” due to his determinacy over his{" "}
            <br />
            principles. Jinnah always stood like a rock in front of his enemies
            and never backed down. In 1933, Jinnah became the leader of the
            Muslim League. In 1940, the Pakistan resolution was drafted by The{" "}
            <br />
            Muslim League at Minar-e-Pakistan. After the Pakistan Resolution was
            passed, Quaid-e-Azam worked tirelessly day and night and did not
            care about his health at all, slowly his health started <br />
            deteriorating but he never stopped working. It was due to
            Quaid-e-Azam’s tireless efforts that Pakistan came into being on the
            1947, 14th of August. Quaid-e-Azam passed away on the 11th of
            September in 1948. <br />
          </p>
          <Image
            className={styles.mylogo}
            src="https://upload.wikimedia.org/wikipedia/commons/8/88/Liaquat_Ali_Khan_1945.jpg"
            alt="Next.js Logo"
            width={75}
            height={75}
            priority
          />
          <center id="liaquat">
            <h1>
              <em>
                <b className={styles.liaquattitle}>{" Liaquat-Ali-Khan "}</b>
              </em>
            </h1>
          </center>
          <br />

          <p className={styles.aboutpara}>
            The great leader and founder of Pakistan. His real name is Mohammad{" "}
            <br />
            Ali Jinnah but widely known as Quaid-e-Azam or Baba-e-Qoum which
            means the father of the nation. Quaid-e-Azam was born on the 25th of
            December in Karachi, in 1876. Quaid-e-Azam was a successful lawyer{" "}
            <br />
            as well as a politician. Quaid-e-Azam’s father’s name was Jinnah
            Poonja and his mother’s name was Mithibai. Quaid-e-Azam belonged to
            a rich merchant family. Quaid-e-Azam received his early education{" "}
            <br />
            from Sindh Madrasa-ul-Islam and a Christian missionary school. He
            was sent to England at the mere age of 16 for higher education and
            later got admission to Lincoln’s Inn Law school to study Law. He{" "}
            <br />
            returned home after studying abroad, then took over managing his
            family business. A few years later, Quaid-e-Azam opened his law firm
            and became a successful lawyer and by 1900, he was appointed as a{" "}
            <br />
            magistrate for the region’s presidency. During this time, Jinnah
            noticed that Hindus and Muslims were united against England, but the
            Hindu leaders had set their interests somewhere else. Soon after{" "}
            <br />
            this Quaid-e-Azam left behind practicing law and went on to join
            political parties so he could take up leadership positions among
            organizations that planned to form Pakistan’s identity. He started{" "}
            <br />
            his political career with Indian National Congress in 1906, then
            after a time span of 7 years, Jinnah joined the Muslim League.
            Quaid-e-Azam was a man with great qualities and leadership. He was a{" "}
            <br />
            human rights activist who constantly fought for the rights of
            Muslims and dedicated his whole life to the liberation of Pakistan.
            He tirelessly worked for the Muslims struggling in India and <br />
            presented their concerns in the 14 points which were rejected by
            Congress. He endured many hardships for the formation of Pakistan
            and the rights of Muslims, but he did not give up. However, his{" "}
            <br />
            efforts did not go unrewarded. Quaid-e-Azam was a man of his word
            and one of the greatest spokesmen. Mahatma Gandhi called
            Quaid-e-Azam “an impossible man” due to his determinacy over his{" "}
            <br />
            principles. Jinnah always stood like a rock in front of his enemies
            and never backed down. In 1933, Jinnah became the leader of the
            Muslim League. In 1940, the Pakistan resolution was drafted by The{" "}
            <br />
            Muslim League at Minar-e-Pakistan. After the Pakistan Resolution was
            passed, Quaid-e-Azam worked tirelessly day and night and did not
            care about his health at all, slowly his health started <br />
            deteriorating but he never stopped working. It was due to
            Quaid-e-Azam’s tireless efforts that Pakistan came into being on the
            1947, 14th of August. Quaid-e-Azam passed away on the 11th of
            September in 1948. <br />
          </p>
        </h4>
      </div>
      <center className={styles.abouthead}>
        {" "}
        <h1>: Quaid-E-Azam :</h1>
      </center>
      <div className={styles.quaidalogodiv}>
        <br />
        <br />
        <br />
        <Image
          className={styles.quaidalogo}
          src="/coi.png"
          alt="Next.js Logo"
          width={250}
          height={250}
          priority
        />
        <Image
          className={styles.quaidblogo}
          src="/coj.png"
          alt="Next.js Logo"
          width={250}
          height={250}
          priority
        />
        <Image
          className={styles.quaidclogo}
          src="/cok.png"
          alt="Next.js Logo"
          width={250}
          height={250}
          priority
        />
        <Image
          className={styles.quaiddlogo}
          src="/col.png"
          alt="Next.js Logo"
          width={250}
          height={250}
          priority
        />{" "}
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <center className={styles.abouthead}>
          {" "}
          <h1>: Mazar-e-Quaid :</h1>
        </center>
        <Image
          className={styles.quaidalogo}
          src="/coa.png"
          alt="Next.js Logo"
          width={300}
          height={300}
          priority
        />
        <Image
          className={styles.quaidblogo}
          src="/cob.png"
          alt="Next.js Logo"
          width={300}
          height={300}
          priority
        />
        <Image
          className={styles.quaidclogo}
          src="/coc.png"
          alt="Next.js Logo"
          width={300}
          height={300}
          priority
        />
        <Image
          className={styles.quaiddlogo}
          src="/cod.png"
          alt="Next.js Logo"
          width={300}
          height={300}
          priority
        />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <center className={styles.abouthead}>
          {" "}
          <h1>: QararDad-e-Pakistan :</h1>
        </center>
        <br />
        <Image
          className={styles.quaidalogo}
          src="/coe.png"
          alt="Next.js Logo"
          width={250}
          height={250}
          priority
        />
        <Image
          className={styles.quaidblogo}
          src="/cof.png"
          alt="Next.js Logo"
          width={250}
          height={250}
          priority
        />
        <Image
          className={styles.quaidclogo}
          src="/cog.png"
          alt="Next.js Logo"
          width={250}
          height={250}
          priority
        />
        <Image
          className={styles.quaiddlogo}
          src="/coh.png"
          alt="Next.js Logo"
          width={250}
          height={250}
          priority
        />
      </div>
      
      <center className={styles.abouthead}>
        {" "}
        <h1>: Location Of Mazar-e-Quaid :</h1>
      </center>
      <br />
      <iframe
        src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14478.737927657829!2d67.0395471!3d24.8746236!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33e5e736977c1%3A0x70ed36c8a6891d3a!2sMazar-e-Quaid!5e0!3m2!1sen!2s!4v1674825500994!5m2!1sen!2s"
        width={1300}
        height={700}
        style={{ border: 5 }}
        allowfullscreen=""
        loading="lazy"
        referrerpolicy="no-referrer-when-downgrade"
      ></iframe>
      <br />
 

      <br />
      <center className={styles.abouthead}>
        {" "}
        <h1>: Follow Us :</h1>
      </center>
      <br />
      <div className={styles.grid}>
        {/* https://www.facebook.com/profile.php?id=100088975870807 */}
        <a
          href="https://www.facebook.com/profile.php?id=100088975870807"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className={inter.className}>
            FaceBook <span>-&gt;</span>
          </h2>
          <p className={inter.className}>Follow us on Facebook.</p>
        </a>
        <a
          href="https://discord.com/invite/ds2ZzR6C"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className={inter.className}>
            Discord <span>-&gt;</span>
          </h2>
          <p className={inter.className}>Follow us on Discord.</p>
        </a>

        <a
          href="https://github.com/RanaRabees?tab=repositories"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className={inter.className}>
            GitHub <span>-&gt;</span>
          </h2>
          <p className={inter.className}>Check Here To See Github.</p>
        </a>
        <a
          href="https://www.linkedin.com/in/rana-rabees-064830251/"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className={inter.className}>
            LinkdIn <span>-&gt;</span>
          </h2>
          <p className={inter.className}>Follow us on LinkdIn.</p>
        </a>
        <a
          href="https://ranarabees.pythonanywhere.com/"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className={inter.className}>
            RBASSA <span>-&gt;</span>
          </h2>
          <p className={inter.className}>More About Us.</p>
        </a>

        <a
          href="https://www.youtube.com/@RanaVerse786/featured"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className={inter.className}>
            Youtube <span>-&gt;</span>
          </h2>
          <p className={inter.className}>Subscribe Our Youtube Channel.</p>
        </a>
      </div>
      <footer>
        <a
          href="https://ranarabees.pythonanywhere.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" RanaVerse "}
          <img src="/favicon.png" alt="RanaVerse" className={styles.logo} />
        </a>
        <br />
      </footer>
      <button>
        <a href="#Hero">
          <img
            id="go"
            src="https://www.wilsoninfo.com/buttons/2019-round-go-button-animation.gif"
            alt="go"
          />
        </a>
      </button>

      <style jsx>{`
        body::selection {
          color: red;
          background-color: rgba(0, 191, 255, 0.4);
        }
        .backLogo {
          border-radius: 50%;
        }
        main {
          padding: 1rem 0;
          flex: 1;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
        }
        mynav {
          position: fixed;
          z-index: 1000;
          left: 0;
          top: 0;
          width: 100vw;
          height: auto;

          border-top: 1px solid #eaeaea;
          display: flex;
          justify-content: center;
          align-items: center;
          background-color: rgba(31, 30, 30, 0.24);
          transition: 0.3s ease background-color;
        }
        // #header {
        //   position: fixed;
        //   z-index: 1000;
        //   left: 0;
        //   top: 0;
        //   width: 100vw;
        //   height: auto;
        // }
        // #header .header {
        //   min-height: 8vh;
        //   background-color: rgba(31, 30, 30, 0.24);
        //   transition: 0.3s ease background-color;
        footer {
          width: 100%;
          height: 100px;
          border-top: 1px solid #eaeaea;
          display: flex;
          justify-content: center;
          align-items: center;
          // background-color: darkkhaki;
          border-radius: 15%;
        }
        #go {
          width: 80px;
          height: 80px;
          position: fixed;
          z-index: 1000;
          margin-right: 30px;
          right: 0;
          bottom: 0;
        }
        #go:hover {
          box-shadow: 0 2.8px 2.2px rgba(0, 0, 0, 0.34),
            0 6.7px 5.3px rgba(0, 0, 0, 0.048),
            0 12.5px 10px rgba(0, 0, 0, 0.06),
            0 22.3px 17.9px rgba(0, 0, 0, 0.072),
            0 41.8px 33.4px rgba(0, 0, 0, 0.086),
            0 100px 80px rgba(0, 0, 0, 0.12);
        }
        footer img {
          margin-left: 0.5rem;
        }
        footer a {
          display: flex;
          justify-content: center;
          align-items: center;
          text-decoration: none;
          color: inherit;
        }
        code {
          background: darkkhaki;
          border-radius: 5px;
          padding: 0.75rem;
          font-size: 1.1rem;
          font-family: Menlo, Monaco, Lucida Console, Liberation Mono,
            DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace;
        }
        code:before,
        code:after {
          content: "";

          box-shadow: 0 2.8px 2.2px rgba(0, 0, 0, 0.34),
            0 6.7px 5.3px rgba(0, 0, 0, 0.048),
            0 12.5px 10px rgba(0, 0, 0, 0.06),
            0 22.3px 17.9px rgba(0, 0, 0, 0.072),
            0 41.8px 33.4px rgba(0, 0, 0, 0.086),
            0 100px 80px rgba(0, 0, 0, 0.12);
        }
      `}</style>

      <style jsx global>{`
        .backLogo {
          border-radius: 50%;
        }
        html,
        body {
          padding: 0;
          margin: 0;
          font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto,
            Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue,
            sans-serif;
        }
        * {
          box-sizing: border-box;
        }
      `}</style>
    </main>
  );
}
